services:
  postgres:
    image: postgres:latest
    container_name: inga-postgres
    environment:
      POSTGRES_DB: inga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inga-backend
    env_file:
      - ./backend/.env.local
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
